######################################################################
# Automatically generated by qmake (3.0) Fri Nov 28 19:19:57 2014
######################################################################

TEMPLATE = app
TARGET = BoardIT_GUI
INCLUDEPATH += .

# Input
HEADERS += boardit.h mythread.h
FORMS += boardit.ui
SOURCES += boardit.cpp main.cpp mythread.cpp
