######################################################################
# Automatically generated by qmake (3.0) Fri Nov 7 17:33:25 2014
######################################################################

TEMPLATE = app
TARGET = BoardIT
INCLUDEPATH += .

# Input
HEADERS += boardit.h mythread.h ui_boardit.h
FORMS += boardit.ui
SOURCES += boardit.cpp main.cpp mythread.cpp
